### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by urskaufmann**
File without rst was a mistake. I dont know how to eliminate from the branch...

File with .rst has to be integrated somewhere in the doc (user guide / digitizing or user guide / new chapter).

### CODE REVIEW

**Comment by sjib** [comment]
You just rename your file delete layer explanation to delete layer explanation.rst.
I would anyway rename all file so that they have no space in the file names - too difficult to reference.

To include it in the doc - the question is, if we want to make a new subfolder https://github.com/QGEP/docs/tree/master/en/user-guide/layerexplanations and add everything there or add it to another chapter.

**Comment by sjib** [comment]
Then you have to edit https://github.com/QGEP/docs/blob/master/en/user-guide/index.rst to connect it to the rest of the docu and copy and index.rst into the new folder. Use e.g. https://github.com/QGEP/docs/blob/master/en/user-guide/digitizing/index.rst as model to adapt for the new folder "layerexplanations"

**Comment by sjib** [comment]
@m-kuhn Can you include this in the master?

**Comment by m-kuhn** [comment]
Sure, thanks

**Pull request merged**
