### PR TITLE
draw attention to Windows pg_service.conf problem + fix

### PR DESCRIPTION
**Pull request by tudorbarascu**

### CODE REVIEW

**Comment by m-kuhn** [comment]
Is there another reason besides the output medium?

Personally, I don't particularly like the gif format. E.g. they are limited in color depth.

**Comment by tudorbarascu** [comment]
No other reason. But they come in handy when doing a walk-through that otherwise would have taken many screen-shots or lot of writing form our part.

**Comment by m-kuhn** [comment]
It's about animations then?
I wonder if we can do something else that has playback controls and better color depth (like html5 video or so). But I don't have a ready-to-use proposal.

**Comment by tudorbarascu** [comment]
Yes. About animations. I like the way Nathan Woodrow presents the latest things he's working on. GIF's come in handy for it. An html5 video would also be nice, but time for research the best way is lacking for all of us probably.

**Comment by m-kuhn** [comment]
I think it's a two-folded thing. On the one hand, an animation gives a good sequential instruction with little screen real-estate. On the other hand having an animation auto-played distracts the reader from the written content (as seen e.g. with advertisement on various pages on the internet)... We could also get started with a platform like vimeo instead of hosting our own html5 videos.

**Pull request merged**
