### PR TITLE
Update deletingobjects.rst

### PR DESCRIPTION
**Pull request by urskaufmann**
Corrections and notes

### CODE REVIEW

**Comment by sjib** [comment]
`.. note:: **Remove part** is misleading. If there are more than parts (e.g. Drainage channels), you can delete also with this tool just the whole detailed geometrie! Do not conform changes, if the result is not what you expect.`

Typing error: `conform` instead of `confirm `

**Comment by sjib** [comment]
Was meinst du mit ` If there are more than parts (e.g. Drainage channels), ...` ?

**Comment by urskaufmann** [comment]
You can draw more than one drainage channel-rectangle for one wastewater-structure object. But you can not delete only one of these rectangles (as the tool-name says).

**Comment by m-kuhn** [comment]
How did you manage to draw multiple drainage channels for one wastewater structure object?
The layer type is "CurvePolygon", so it won't allow to digitize more than one single part in the geometry.

**Comment by urskaufmann** [comment]
You are right, I am not able to draw these in QGEP. I have imported this data...

**Comment by m-kuhn** [comment]
Even with the import I wonder how this happened, the database shouldn't allow that.
It's probably two separate structures?

**Comment by urskaufmann** [comment]
No, is it not. Import was possible!
This is a part of the xtf I use as import
      <DSS.Siedlungsentwaesserung.Normschacht TID="xBDE00NS3895">
        <OBJ_ID>BDE00NS3895</OBJ_ID>
        <BaulicherZustand>Z4</BaulicherZustand>
        <Bezeichnung>0879.230.0002</Bezeichnung>
        <Detailgeometrie>
          <SURFACE>
            <BOUNDARY>
              <POLYLINE>
                <COORD><C1>603034.423</C1><C2>184303.266</C2></COORD>
                <COORD><C1>603034.247</C1><C2>184303.361</C2></COORD>
                <COORD><C1>603035.001</C1><C2>184304.770</C2></COORD>
                <COORD><C1>603035.177</C1><C2>184304.675</C2></COORD>
                <COORD><C1>603034.423</C1><C2>184303.266</C2></COORD>
              </POLYLINE>
            </BOUNDARY>
            <BOUNDARY>
              <POLYLINE>
                <COORD><C1>603037.510</C1><C2>184306.008</C2></COORD>
                <COORD><C1>603037.708</C1><C2>184305.977</C2></COORD>
                <COORD><C1>603037.529</C1><C2>184304.826</C2></COORD>
                <COORD><C1>603037.332</C1><C2>184304.857</C2></COORD>
                <COORD><C1>603037.510</C1><C2>184306.008</C2></COORD>
              </POLYLINE>
            </BOUNDARY>
          </SURFACE>
        </Detailgeometrie>

In QGIS it looks like this: (selected, but I can not do a rightclick with the vertex-tool)
Anmerkung 2021-02-01 131829

And in pgadmin it looks like this:
Anmerkung 2021-02-01 131753

**Pull request closed without merging**
