### PR TITLE
new how-to chapter in user guide

### PR DESCRIPTION
**Pull request by urskaufmann**
please insert this in the user guide. Chapter how-to or various or .... (who has a good name for this)?

### CODE REVIEW

**Comment by sjib** [comment]
en/user-guide/How-To/images/t - is this needed?

**Comment by sjib** [comment]
Else it looks nice to me

**Comment by sjib** [comment]
I would suggest to add it as chapter 2.7 How to

**Comment by urskaufmann** [comment]
> en/user-guide/How-To/images/t - is this needed?

No. I could not delete the file

**Comment by m-kuhn** [comment]
Deleted

**Comment by sjib** [comment]
Adapt index file user-guide so that new chapter shows up

**Pull request merged**
