### PR TITLE
add grant on all sequences

### PR DESCRIPTION
**Pull request by TriformDaniel**
otherwise editing not possible

### CODE REVIEW

**Comment by TriformDaniel** [comment]
@m-kuhn good enough for you?

**Comment by m-kuhn** [comment]
Thanks @TriformDaniel 
I think it would be good to completely synchronize this with the database setup script and remove the grants to the postgres user.

**Comment by TriformDaniel** [comment]
?
Which database setup script?
I put the line in the proposed batch script under [1.3.1.2. Empty data model](https://qgep.github.io/docs/installation-guide/database-initialization.html#empty-data-model)

**Comment by m-kuhn** [comment]
I think this text here should be the same as

https://github.com/QGEP/docs/pull/115/files#diff-e0b1ff27d1b3c001a6abfc3f1be3f9bbR152-R167

Right now the documentation is giving controversial information

**Pull request merged**
