### PR TITLE
1.3.1.1 Windows pg_service

### PR DESCRIPTION
**Pull request by max-trolliet**
It is not clear if the environmental variables has to be set in QGIS or in Windows. 

This step comes before installing QGIS, but I did an instal on my personal computer, added the variable to QGIS only and it seems to be working.

### CODE REVIEW

**Comment by andreasneumann** [comment]
@max-trolliet It does not matter where the variable is set (either on the machine, on a per user base in the operating system) or in QGIS

At the end, all that matters, is that QGIS can see this variable.

On very restricted operating systems / policies, the QGIS way of setting env vars may be the only way. On more open systems you can set in in the OS.

**Comment by m-kuhn** [comment]
Should we document one way that always works (i.e. setting the var in QGIS) and add a note that it's also possible to do it on the system?

**Comment by andreasneumann** [comment]
I would suggest to document different options - as defining it centrally is more efficent than in every users QGIS profile. It all depends on the circumstances and how the organization works.

But yes - setting it in QGIS will always work - but requires a restart of QGIS after you set it.

**Comment by m-kuhn** [comment]
@max-trolliet can you document the way you are doing it now?

**Pull request closed without merging**
