### PR TITLE
updated vm docs + fix some sphinx-doc warnings

### PR DESCRIPTION
**Pull request by tudorbarascu**

### CODE REVIEW

**Comment by m-kuhn** [comment]
Hey @tudorbarascu any chance to rebase that?
Sorry it took so long, I'd be happy to merge that.

**Comment by tudorbarascu** [comment]
@m-kuhn Sure! No worries!
It will take a week though as I want to do some updates!

**Comment by m-kuhn** [comment]
Wait, too easy, I could do it with the online editor

**Comment by m-kuhn** [comment]
Merge it?

**Pull request merged**
