### PR TITLE
added VM docs

### PR DESCRIPTION
**Pull request by tudorbarascu**
There is still work to be done describing the VM installation + the options on how to install it on a stick or another storage but It's enough for now in case anyone wants to just run the QGEP demo.

### CODE REVIEW

**Comment by tudorbarascu** [comment]
Thanks, I didn't had the time to install the qgis web client, will do it in a few days time.

**Comment by m-kuhn** [comment]
How much time does it take you to create a new VM?
Just wondering, the datamodel is undergoing some major changes now and it would be nice to ship the new version with the VM. (Not 100% ready yet)

**Comment by tudorbarascu** [comment]
As I'm using snapshots a lot, it takes a really small amount of my time for future add ons (30 minutes tops).
After that, there's also the compression time (little over 1 hour on my notebook) + uploading to the file server (5-10 minutes) if I'm not in the internal network.
Basically, I can add enhancements as we go, being few hours late after the data model.

**Comment by tudorbarascu** [comment]
Thanks for the suggestion. Indeed it would be really nice. Will do it tomorrow.

**Pull request merged**
