### PR TITLE
Pum update

### PR DESCRIPTION
**Pull request by tproduit**
* add git command to select the release

### CODE REVIEW

**Comment by sjib** [comment]
@olivierdalang Can this be merged?

**Comment by olivierdalang** [comment]
Maybe we could tell users to download the archive (`https://github.com/QGEP/datamodel/archive/refs/tags/1.5.4.zip`) instead of checking out from git. It should be the same files but slightly less error prone (also less risks of line-endings or similar nasty issues)

**Comment by tproduit** [comment]
Ok for me to tell the user to download the archive rather than using git. @olivierdalang can you do the change and the merge?

**Comment by olivierdalang** [comment]
Done here : https://github.com/QGEP/docs/pull/151

**Pull request closed without merging**
